/**
 *
 * $Id$
 */
package jsonToSql.validation;

import jsonToSql.Connection;
import jsonToSql.MergedField;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jsonToSql.Config}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConfigValidator {
	boolean validate();

	boolean validateConecction(Connection value);
	boolean validateMergeFields(EList<MergedField> value);
}
