/**
 *
 * $Id$
 */
package jsonToSql.validation;

import jsonToSql.AttributeName;
import jsonToSql.Field;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jsonToSql.MergedField}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MergedFieldValidator {
	boolean validate();

	boolean validateTableName(String value);
	boolean validateAttributeNames(EList<AttributeName> value);
	boolean validateFields(EList<Field> value);
}
