/*
* generated by Xtext
*/
package co.edu.uniandes.jsonToSql.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import co.edu.uniandes.jsonToSql.services.GrammarGrammarAccess;

public class GrammarParser extends AbstractContentAssistParser {
	
	@Inject
	private GrammarGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected co.edu.uniandes.jsonToSql.ui.contentassist.antlr.internal.InternalGrammarParser createParser() {
		co.edu.uniandes.jsonToSql.ui.contentassist.antlr.internal.InternalGrammarParser result = new co.edu.uniandes.jsonToSql.ui.contentassist.antlr.internal.InternalGrammarParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getFieldTypeAccess().getAlternatives(), "rule__FieldType__Alternatives");
					put(grammarAccess.getConfigAccess().getGroup(), "rule__Config__Group__0");
					put(grammarAccess.getConfigAccess().getGroup_6(), "rule__Config__Group_6__0");
					put(grammarAccess.getConfigAccess().getGroup_6_3(), "rule__Config__Group_6_3__0");
					put(grammarAccess.getConnectionAccess().getGroup(), "rule__Connection__Group__0");
					put(grammarAccess.getConnectionAccess().getGroup_2(), "rule__Connection__Group_2__0");
					put(grammarAccess.getConnectionAccess().getGroup_3(), "rule__Connection__Group_3__0");
					put(grammarAccess.getConnectionAccess().getGroup_4(), "rule__Connection__Group_4__0");
					put(grammarAccess.getMergedFieldAccess().getGroup(), "rule__MergedField__Group__0");
					put(grammarAccess.getMergedFieldAccess().getGroup_1(), "rule__MergedField__Group_1__0");
					put(grammarAccess.getMergedFieldAccess().getGroup_5(), "rule__MergedField__Group_5__0");
					put(grammarAccess.getMergedFieldAccess().getGroup_10(), "rule__MergedField__Group_10__0");
					put(grammarAccess.getAttributeNameAccess().getGroup(), "rule__AttributeName__Group__0");
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getConfigAccess().getConecctionAssignment_5(), "rule__Config__ConecctionAssignment_5");
					put(grammarAccess.getConfigAccess().getMergeFieldsAssignment_6_2(), "rule__Config__MergeFieldsAssignment_6_2");
					put(grammarAccess.getConfigAccess().getMergeFieldsAssignment_6_3_1(), "rule__Config__MergeFieldsAssignment_6_3_1");
					put(grammarAccess.getConnectionAccess().getUrlAssignment_2_1(), "rule__Connection__UrlAssignment_2_1");
					put(grammarAccess.getConnectionAccess().getUsernameAssignment_3_1(), "rule__Connection__UsernameAssignment_3_1");
					put(grammarAccess.getConnectionAccess().getPasswordAssignment_4_1(), "rule__Connection__PasswordAssignment_4_1");
					put(grammarAccess.getMergedFieldAccess().getTableNameAssignment_1_1(), "rule__MergedField__TableNameAssignment_1_1");
					put(grammarAccess.getMergedFieldAccess().getFieldsAssignment_4(), "rule__MergedField__FieldsAssignment_4");
					put(grammarAccess.getMergedFieldAccess().getFieldsAssignment_5_1(), "rule__MergedField__FieldsAssignment_5_1");
					put(grammarAccess.getMergedFieldAccess().getAttributeNamesAssignment_9(), "rule__MergedField__AttributeNamesAssignment_9");
					put(grammarAccess.getMergedFieldAccess().getAttributeNamesAssignment_10_1(), "rule__MergedField__AttributeNamesAssignment_10_1");
					put(grammarAccess.getAttributeNameAccess().getOldFieldAssignment_1(), "rule__AttributeName__OldFieldAssignment_1");
					put(grammarAccess.getAttributeNameAccess().getFinalFieldAssignment_3(), "rule__AttributeName__FinalFieldAssignment_3");
					put(grammarAccess.getFieldAccess().getNameAssignment_1(), "rule__Field__NameAssignment_1");
					put(grammarAccess.getFieldAccess().getTypeAssignment_3(), "rule__Field__TypeAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			co.edu.uniandes.jsonToSql.ui.contentassist.antlr.internal.InternalGrammarParser typedParser = (co.edu.uniandes.jsonToSql.ui.contentassist.antlr.internal.InternalGrammarParser) parser;
			typedParser.entryRuleConfig();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GrammarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GrammarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
