/*
 * generated by Xtext
 */
package co.edu.uniandes.jsonToSql.ui.contentassist

import co.edu.uniandes.jsonToSql.ui.contentassist.AbstractGrammarProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GrammarProposalProvider extends AbstractGrammarProposalProvider {
}
