/*
 * generated by Xtext
 */
package co.edu.uniandes.jsonToSql;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GrammarRuntimeModule extends co.edu.uniandes.jsonToSql.AbstractGrammarRuntimeModule {

}
