/*
 * generated by Xtext
 */
package co.edu.uniandes.jsonToSql.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import co.edu.uniandes.jsonToSql.ui.internal.GrammarActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GrammarExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GrammarActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GrammarActivator.getInstance().getInjector(GrammarActivator.CO_EDU_UNIANDES_JSONTOSQL_GRAMMAR);
	}
	
}
